### ISSUE TITLE
Error with Linear Tree Formulation: "ModuleNotFoundError" despite module presence

### ISSUE THREAD

**Issue by bahar239** [cog-imperial/OMLT#134]
Hello,

While working with the 'Linear Tree Formulations' notebook, I always encounter the error: "ModuleNotFoundError: No module named 'omlt.linear_tree'". The module is visible in the directory structure. My environment is a MacBook Pro with an Apple M1 chip, 16 GB RAM, running Python version 3.9.13. Any assistance or solutions regarding this 'Linear Tree Formulations' error would be appreciated.

**Comment by rmisener** [comment]
@bammari, Are you able to take a look at this one? @bahar239 may be available to chat more about this and it's useful to get feedback on the linear tree components so quickly.

**Comment by bammari** [comment]
Hi @bahar239 and thank you for your comment.

Can you please give me more information on the Jupyter kernel you are using to run this notebook? Specifically, if you are using a virtual environment, how did you install omlt?

**Comment by jalving** [comment]
@bahar239 can you check if you have `linear-tree` installed?  If not, try running `pip install linear-tree`
I noticed this error came up when updating the docs. I think this [line](https://github.com/cog-imperial/OMLT/blob/b9600e2064b70bef981fdecc725785d30688dae5/src/omlt/linear_tree/lt_definition.py#L2C18-L2C18) is the culprit since we do not check for `linear-tree` on import and it isn't an `omlt` requirement.

**Comment by bahar239** [comment]
Hi @bammari, I'm running the Jupyter Notebook within a Conda virtual environment. I installed it using `pip install omlt` within this environment.

**Comment by bahar239** [comment]
Hi @jalving. Yes, linear-tree is installed.

**Comment by bahar239** [comment]
@bammari thank you so much! Following your advice, I don't get that error anymore. Appreciate the guidance!

**Comment by bammari** [comment]
@bahar239 Glad to help!
